-- =============================================================
-- Idempotent payment inserts
--
-- client_request_id is generated by the app before inserting a payment.
-- The unique constraint lets duplicate retries no-op at the client while
-- preserving the existing paid_cents trigger/status behavior.
-- =============================================================

alter table public.payments
  add column if not exists client_request_id text;

do $$
begin
  alter table public.payments
    add constraint payments_client_request_id_key unique (client_request_id);
exception
  when duplicate_object then null;
end $$;
